[FEATURE] 8 CustomerService
CSC207-2022F-UofT/course-project-6-2 pull request #13
Opened 2022-11-14 20:15 UTC by TingmingFan

## Description
Feature 8 CustomerService, created 6 Q&A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-11-15 00:51 UTC, donnaqi commented on src/main/java/CustomerService/CustomerService.java
> +    JButton b=new JButton("How can I sell my product in your store");
Make sure every question ends with a question mark to make it consistant with other question buttons.

2022-11-15 00:53 UTC, donnaqi commented on src/main/java/CustomerService/CustomerService.java
> +    b.addActionListener(e -> tf.setText("Register on our web for the flexibility to sell one item or thousands.\n" +
It would be better to change "web" to "app"

2022-11-15 00:54 UTC, donnaqi commented on src/main/java/CustomerService/CustomerService.java
> +    x.addActionListener(e -> tf.setText("Once you place an order on the website, you'll shortly "));
This answer is incomplete.

2022-11-15 00:55 UTC, donnaqi commented on src/main/java/CustomerService/CustomerService.java
> +    y.addActionListener(e -> tf.setText("Shipping fees depend on whether you plan to fulfill orders yourself," +
Not sure if this answer make sense.

2022-11-15 00:56 UTC, donnaqi commented on src/main/java/CustomerService/CustomerService.java
> +    JButton z =new JButton(" What items can not be sold in your store? ");
It might make more sense if you change "your store" to either "my store" or "your app".

2022-11-15 01:04 UTC, donnaqi requested changes
Try to work more on code structre, i.e. seperate blocks of code using empty line/white space to make the code more readable.

2022-11-18 05:29 UTC, donnaqi approved these changes
LGTM

2022-11-18 05:53 UTC, yuanjiat approved these changes
Greet work of adding the customer service feature. Successfully set the FAQ.

2022-11-18 05:57 UTC, sanciag17 approved these changes
Good FAQ's. Nice Job!

2022-11-18 06:06 UTC, merged