Feature 5 order history shopping cart
CSC207-2022F-UofT/course-project-6-2 pull request #41
Opened 2022-11-30 06:19 UTC by sanciag17

## Description
 Finish ShoppingCartPanel and modified OrderHistoryPanel. Fixed the issue where we needed to refresh the frame to get the latest data for orders, drinks etc. As well as connect shopping cart with the drinks so now we can add the drinks to shopping cart. Can also re-order from order history
 #4 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2022-11-30 07:56 UTC, donnaqi requested changes
Still need to fix bug in Order History Section. Shopping Cart Section looks good now!

2022-12-01 04:05 UTC, donnaqi approved these changes
Interface looks good! All the functionality work now. Good job!

2022-12-01 04:08 UTC, yyuan-qin approved these changes

2022-12-01 04:12 UTC, lisa272 approved these changes
good work modify the customer and seller screens

2022-12-01 04:13 UTC, merged