Tests 7
CSC207-2022F-UofT/course-project-6-2 pull request #42
Opened 2022-11-30 08:01 UTC by AdwinTazement

## Description
Fixed some bugs in WarningBoard and GetWarningMessage, completed the test for customer, GetWarningMessage, LoginUser, Order, RegisterUser( The test for succesfully registered is not written), ResetUpperPassword, and ShoppingCart.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings

2022-11-30 23:07 UTC, donnaqi requested changes
Please make sure to change the function that failed your tests before merging into main branch.

2022-12-01 04:08 UTC, donnaqi approved these changes

2022-12-01 04:22 UTC, sanciag17 approved these changes

2022-12-01 04:24 UTC, yyuan-qin approved these changes

2022-12-01 04:25 UTC, merged